version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/perdayonespoon/ # 프로젝트 이름
    overwrite: yes
file_exists_behavior: OVERWRITE

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: scripts/run_new_was.sh
      timeout: 300
      runas: ec2-user
    - location: scripts/health_check.sh
      timeout: 300
      runas: ec2-user
    - location: scripts/switch.sh
      timeout: 300
      runas: ec2-user